# Site
repository: shubhiigupta/shubhiigupta.github.io
favicon: images/favicon.ico

# Personal info
name: Shubhi Gupta
title: Computer Science Undergradute
email: shubhi.99gupta@gmail.com
website: shubhiigupta.github.io

darkmode: false

# Social links
twitter_username: catthatcodes
github_username:  shubhiigupta
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: shubhigupta99
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/shubhi1.jpg
about_content: | # this will include new lines to allow paragraphs




  Hi! My name’s Shubhi and I am a computer science undergraduate at SRM Institute of Science and Technology, studying image processing, statistics and neural networks, striving to develop fun and friendly solutions in automation.

  Aided with my hyperactive imagination, I spend quality time in digital and 3D art and take quite the delight in conducing my version of the cities from the 31st century and sometimes even ramen bowls.

  I am personally attached to the quote - <mark>"Curiosity killed the cat, but satisfaction brought it back."</mark>

# Education Section
# educaton_title: Education

# Experience Section
# experience_title: Experience

# More Section
# more_title: Skills
more_content: | # this will include new lines to allow paragraphs
  Languages
   - Python
   - C++
  Frameworks
   - OpenCV
   - Tensorflow
   - Keras
   - Scikit-learn
   - NumPy
   - Excel

# Projects Section
# projects_title: Projects



# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
